
skillMetadata:
  sections:
    - name: Connect to Neo4j
      fields:
        - name: connect_url
          type: text
          label: Connect URL
          value: "neo4j+s://c8cb96e7.databases.neo4j.io"
          placeholder: demo prompt in the input box
    - name: Authentication
      fields:
        - type: text
          label:
        - name: username
          type: text
          label: Username
          value: "neo4j"
        - name: password
          type: password
          label: Password
          value: "n96qz1OkNxmJSES7LBiVUSGbYrRa0jKIUm30NBrM1HY"